### ISSUE TITLE
Filtering issue for Things: $filter=properties/fieldname eq value does not work

### ISSUE THREAD

**Issue by sorenp** [FraunhoferIOSB/SensorThingsServer#2]
This is probably a trivial question, but I need a bit of help to get further.

I have created several Things on the Server that one of my colleges have built and set up. One of the properties I have added for the Things is the field named "template".

An examples Thing has the following JSON content:

{
  "name": "My Thing",
  "description": "A Test Thing",
  "properties": {
    "TestModel": "XXX-v1.0",
    "name": "My models name",
    "type": "type of smart sensor",
    "supplier": "Blenda Corp",
    "template": "true"
  },
  "Locations@iot.navigationLink": "http://sthing-app.falster.io:8080/SensorThingsServer-1.0/v1.0/Things(9)/Locations",
  "HistoricalLocations@iot.navigationLink": "http://sthing-app.falster.io:8080/SensorThingsServer-1.0/v1.0/Things(9)/HistoricalLocations",
  "Datastreams@iot.navigationLink": "http://sthing-app.falster.io:8080/SensorThingsServer-1.0/v1.0/Things(9)/Datastreams",
  "MultiDatastreams@iot.navigationLink": "http://sthing-app.falster.io:8080/SensorThingsServer-1.0/v1.0/Things(9)/MultiDatastreams",
  "@iot.id": 9,
  "@iot.selfLink": "http://sthing-app.falster.io:8080/SensorThingsServer-1.0/v1.0/Things(9)"

I now want to filter my request for Things, so I only get those where the property template is true.

From reading OData documentation I expect to be able to GET the following URL:

http://sthing-app.falster.io:8080/SensorThingsServer-1.0/v1.0/Things(9)?$filter=properties/template eq 'true'

However, the response I get from the SensorThings API server is 
"Unexpected 'I'"

Am I doing something wrong?
Is there some configuration lacking? (filtering works fine on top level fields like name)
Is this a bug?

Hoping somebody can help here. Thanks!

**Comment by hylkevds** [comment]
The error message "Unexpected 'I'" is a bit unexpected, I would expect a "Invalid query: Query is not valid." since filtering on fields in properties is not yet supported.

I'm guessing you're filtering all Things, not just Thing(9) :)

For now you can try 
`$filter=substringof(%27"template":"true"%27,properties)`

It will do a string search on the json object stored for the properties field. Far from ideal, since it's not very reliable.
I'll mark this as a feature request.

**Comment by sorenp** [comment]
Yes - I want to filter all things, not just Thing(9) :)

Thank you for your response. I was not quite clear on how deep the conformance requirements for filtering goes. 
To provide a bit more information on my use case I want to model types of devices as templates, which a provisioning client then can look up, select the appropriate template, and then use this template to instantiate a new model for the provisioned device. Thanks

**Comment by hylkevds** [comment]
That sounds like an interesting use-case.

Currently a more reliable option would be to prefix the name of these templates with "template-" or something like that.

The conformance tests currently do not check if filtering on sub-properties works. While implementing this I'll create some tests for it in our branch of the conformance tests, and create a pull request for it. That should get a discussion started about it.

**Comment by sorenp** [comment]
Thank you for the advice.
In my current experiments I have prefixed the Thing description with "@Template@".

Thank you for your plan to extend your tests

**Comment by sorenp** [comment]
Shall I keep this open or do you prefer to have it closed?

**Comment by hylkevds** [comment]
I've added some first support for filtering and ordering on json properties. Please give the latest version a spin and let me know if it works as you expect.

PostgreSQL always treats json properties as text, so ordering on  numeric properties will order them in string order (0,1,10,11,2,3).

We also need to look into converting the columns that hold json string to jsonb to increase performance.

Please keep this issue open, I'll close it when I'm happy with the implementation :)

**Comment by sorenp** [comment]
Great! My Dev team is off on vacation so it will probably be a week or so before I can have your new version up and run.

**Comment by Jimlikezebra** [comment]
Hi hylkevds
I find out a problem.
if you use the following URL:
http://localhost:8080/SensorThingsServer/v1.0/Things(9)?$filter=properties/name eq 'My models name'
the response I get from the latest version is Unexpected 'I'.

Hoping somebody can help here. Thanks!

**Comment by hylkevds** [comment]
It seems I only pushed the commit to the intervalFunctions branch. I've now also pushed it to the master branch.

There is a second issue in that it currently doesn't like it if a property has a key that is also used as an entityproperty in SensorThings API. So properties/name doesn't currently work, since "name" is an entityProperty, likewise properties/Things also doesn't work, since Things is a navigationProperty.

**Comment by hylkevds** [comment]
It should work now on the latest version of the master branch.

**Comment by Jimlikezebra** [comment]
Thank you for your response. 
It work.

**Comment by sorenp** [comment]
Hi Hylke van der Schaaf,
I have now tried your latest version, and it works as I expect.
Good work.

**Comment by hylkevds** [comment]
The latest version now has full support for accessing json properties, including accessing arrays and dealing with mixed data types.

**Comment by geoxanadu** [comment]
Hello,

unfortunately I would like the reopen this for a minor inquiry. Requesting "$filter=properties/fieldname eq value" where the fieldname contains underscores i.e. "external_project_id" yields in an error. Without underscores everything works. Since I would like to keep everything in lower case I think the possibility of underscores will help for a better clarity/usability of the keys.

**Comment by hylkevds** [comment]
I've added the underscore to the list of allowed characters in names.
