### ISSUE TITLE
Do we have support for using geo.distance() filter on Observation result

### ISSUE THREAD

**Issue by sudhamani1983** [FraunhoferIOSB/SensorThingsServer#23]
We are receiving things geographical location point via Observation. Do we have support for using geo.distance() filter on Observation result.

**Comment by hylkevds** [comment]
That's not possible, unfortunately. You will have to put the location in the FeatureOfInterest of the Observation, or update the Location of the Thing.

**Comment by sudhamani1983** [comment]
I put location in FeatureOfInterest  of the Observation. I am trying to use geospatial function like below. But getting error response with status code 400. 

http://localhost:8080/SensorThingsService/v1.0/Datastreams(41)/Observations?$expand=FeatureOfInterest($filter=geo.distance(FeatureOfInterest/feature, geography'POINT (103.83233428 1.3037227)') gt 100)

(or)

http://localhost:8080/SensorThingsService/v1.0/Datastreams(41)/Observations?$expand=FeatureOfInterest($filter=geo.distance(feature, geography'POINT (103.83233428 1.3037227)') gt 100)

**Response for both request:** 
Unexpected 'I'

**Comment by hylkevds** [comment]
What version are you using? With your queries I get
`Illegal operation: Could not convert parameter of type com.querydsl.core.types.dsl.StringPath to type com.querydsl.spatial.GeometryExpression`
because we've got a bug in the FoI filter...

That said, I don't think your query expresses what you want to do. 
`v1.0/Datastreams(41)/Observations?$expand=FeatureOfInterest($filter=geo.distance(feature, geography'POINT (103.83233428 1.3037227)') gt 100)`
This query fetches all observations for Datastream 41, and then for each Observation, expands the FoI, but  only if that FoI is further away than 100 units.
So you always get all Observations, but only for some the FoI.

You probably want this query:
`v1.0/Datastreams(41)/Observations?$expand=FeatureOfInterest&$filter=geo.distance(FeatureOfInterest/feature, geography'POINT (103.83233428 1.3037227)') gt 100`
Fetch all Observations, filtered by distance, and expand the FoI.

That also currently gives the same error, due to the bug I mentioned.

**Comment by hylkevds** [comment]
Filtering on FeatureOfInterest/feature now works.

**Comment by sudhamani1983** [comment]
Thank you. I took changes and tested. Working fine. Version 1.2-SNAPSHOT. 

![image](https://user-images.githubusercontent.com/29911144/31977430-72ec3f36-b96f-11e7-86e6-b29c5a18f4ea.png)

**Comment by hylkevds** [comment]
Excellent.
